spring.datasource.url=jdbc:mysql://localhost:3306/moodsync
spring.datasource.username=root
spring.datasource.password=Chir@3175

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080 